name: Playwright Enterprise Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install

    - run: npx playwright install --with-deps

    - run: npx playwright test

    # Upload Playwright reports, traces, videos, screenshots
    - name: Upload Playwright artifacts
      if: always()   # ensures artifacts are uploaded even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: |
          playwright-report
          test-results/
          traces/
          videos/